services:
  - type: web
    name: chess-websocket-server
    env: node
    buildCommand: npm install
    startCommand: node simple-websocket-server.js
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: PORT
        value: 10000 