name = "lawb-chess-api"
main = "functions/api/stockfish.js"
compatibility_date = "2024-01-01"

[env.production]
name = "lawb-chess-api"

[env.staging]
name = "lawb-chess-api-staging"

[[env.production.routes]]
pattern = "api.lawb.xyz/stockfish"
zone_name = "lawb.xyz"

[[env.staging.routes]]
pattern = "api-staging.lawb.xyz/stockfish"
zone_name = "lawb.xyz" 